# Generated by Django 5.0.1 on 2024-01-14 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="status",
            field=models.IntegerField(default=0),
        ),
    ]
